FROM ollama/ollama:latest

RUN apt-get update && apt-get install -y curl

COPY ollama_pull_model.sh /usr/local/bin/ollama_pull_model.sh
RUN chmod +x /usr/local/bin/ollama_pull_model.sh

ENTRYPOINT ["/usr/local/bin/ollama_pull_model.sh"]